### ISSUE TITLE
synccheck获取到的状态一直是新消息

### ISSUE THREAD

**Issue by loocao** [LittleYann/wxbot#1]
请求synccheck一直返回数据"window.synccheck={retcode:"0",selector:"2"}",然后调用webwxsync也一直能拿到新消息,请问这个要怎么解决?

**Comment by m9d2** [comment]
什么意思？是一直获取到的是同一个消息吗？

**Comment by LittleYann** [comment]
@

**Comment by m9d2** [comment]
@oncereply

**Comment by loocao** [comment]
已经解决了,每次调用synccheck传入的synckey参数都是变动的
参照了这个:[http://blog.csdn.net/wonxxx/article/details/51787041#2-获取最新消息webwxsync](http://blog.csdn.net/wonxxx/article/details/51787041#2-获取最新消息webwxsync)
